fix: `set_timezone` issue
Fix error when offset starts with '+' or '-':

```
thread 'tokio-runtime-worker' panicked at 'called Result::unwrap() on an Err value: "Timezone information not found"', src/util/calculator.rs:26:32

note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

For example for `Asia/Almaty` (located in Kazakhstan) `offset_from_utc_date` returns "+6" rather than "GMT+6".

This leads to an error beacuse Regex in Smartcalc expects offset with `GMT` in string:

https://github.com/erhanbaris/smartcalc/blob/cd39b590aba74e8ca326ba78acea488d0550a3e8/src/json/config.json#L35